<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>

        <BaseOutputPath>$(MSBuildProjectDirectory)\Build\</BaseOutputPath>

        <!-- Keep paths tidy -->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <MonoGamePlatform>DesktopVK</MonoGamePlatform>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Icon.ico"/>
        <None Remove="Icon.bmp"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Icon.ico">
            <LogicalName>Icon.ico</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Icon.bmp">
            <LogicalName>Icon.bmp</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\MonoGame\MonoGame.Framework\MonoGame.Framework.Native.csproj" />
      <ProjectReference Include="..\MonoGame\src\NuGetPackages\MonoGame.Runtime.Windows.Vulkan\MonoGame.Runtime.Windows.Vulkan.csproj" />
      <ProjectReference Include="..\MonoGame\src\NuGetPackages\MonoGame.Runtime.Mac.Vulkan\MonoGame.Runtime.Mac.Vulkan.csproj" />
      <ProjectReference Include="..\MonoGame\src\NuGetPackages\MonoGame.Runtime.Linux.Vulkan\MonoGame.Runtime.Linux.Vulkan.csproj" />
      <ProjectReference Include="..\Dreambit.Content\Dreambit.Content.csproj" ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\Dreambit.Examples.Content\Dreambit.Examples.Content.csproj" ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\DreambitEngine\DreambitEngine.csproj" />
    </ItemGroup>
    <ItemGroup>
      <UpToDateCheckInput Include="..\Dreambit.Content\Assets\**\*" />
      <UpToDateCheckInput Include="..\Dreambit.Examples.Content\Assets\**\*" />
    </ItemGroup>
    <Import Project="..\Dreambit.Content\BuildContent.targets" />
    <Import Project="..\Dreambit.Examples.Content\BuildContent.targets" />
</Project>
