<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>AssetBaker</AssemblyName>

        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>

        <BaseOutputPath>$(MSBuildProjectDirectory)\Build\</BaseOutputPath>

        <!-- Keep paths tidy -->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NLayer" Version="2.0.1" />
      <PackageReference Include="NJsonSchema" Version="11.4.0" />
        <PackageReference Include="NVorbis" Version="0.10.5" />
      <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
      <PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.5" />
      <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5" />
      <PackageReference Include="Spectre.Console" Version="0.57.2" />
      <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
      <PackageReference Include="YamlDotNet" Version="18.1.0" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="..\Dreambit.Content\Assets\Effects\*.fx"
                        Link="BuiltInContent\Effects\%(Filename)%(Extension)" />
      <EmbeddedResource Include="..\Dreambit.Content\Assets\Fonts\*.ttf"
                        Link="BuiltInContent\Fonts\%(Filename)%(Extension)" />
    </ItemGroup>
</Project>
