<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Content.Pipeline" />
    <PackageReference Include="MonoGame.Framework.Native" PrivateAssets="all" />
    <PackageReference Include="MonoGame.Library.FreeType" />
    <PackageReference Include="MonoGame.Library.MojoShader" />
    <PackageReference Include="MonoGame.Tool.Basisu" />
    <PackageReference Include="MonoGame.Tool.Crunch" />
    <PackageReference Include="MonoGame.Tool.Dxc" />
    <PackageReference Include="MonoGame.Tool.FFmpeg" />
    <PackageReference Include="MonoGame.Tool.FFprobe" />
  </ItemGroup>
</Project>
